# Generated by Django 2.2.7 on 2019-12-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=250)),
                ('dateofbirth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(choices=[('RW', 'Rwanda'), ('UG', 'Uganda'), ('BU', 'Burundi'), ('TZ', 'Tanzania')], max_length=3)),
            ],
        ),
    ]
