# Generated by Django 2.2.7 on 2019-12-01 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
