# Generated by Django 3.0 on 2019-12-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makas', '0002_auto_20191201_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='dateofbirth',
            field=models.DateField(blank=True),
        ),
    ]
