# Generated by Django 3.0 on 2019-12-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makas', '0003_auto_20191215_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='dateofbirth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
