# Generated by Django 3.0 on 2019-12-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makas', '0005_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='dateofbirth',
        ),
        migrations.AddField(
            model_name='users',
            name='online',
            field=models.CharField(default='no', max_length=3),
        ),
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
