# Generated by Django 3.0 on 2019-12-17 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makas', '0006_auto_20191217_0709'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Members',
        ),
    ]
