# Generated by Django 3.0 on 2019-12-17 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makas', '0007_auto_20191217_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='posttitme',
            field=models.TimeField(default=datetime.time),
        ),
    ]
