# Generated by Django 3.0 on 2019-12-17 09:15

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('makas', '0009_auto_20191217_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='nowdate',
            field=models.DateField(auto_created=datetime.date, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posts',
            name='posttitme',
            field=models.TimeField(auto_created=datetime.time),
        ),
    ]
