# Generated by Django 3.0 on 2019-12-17 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makas', '0010_auto_20191217_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='nowdate',
        ),
        migrations.AlterField(
            model_name='posts',
            name='posttitme',
            field=models.TimeField(auto_created=datetime.time, default=datetime.time),
        ),
    ]
