# Generated by Django 3.0 on 2019-12-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makas', '0013_auto_20191217_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='attachements',
            field=models.ManyToManyField(blank=True, to='makas.PostAttachments'),
        ),
    ]
