# Generated by Django 3.0 on 2019-12-17 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makas', '0014_auto_20191217_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='attachements',
        ),
        migrations.AddField(
            model_name='postattachments',
            name='postis',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='makas.Posts'),
            preserve_default=False,
        ),
    ]
