# Generated by Django 3.0 on 2019-12-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makas', '0015_auto_20191217_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postattachments',
            name='attachment',
            field=models.FileField(upload_to='post/'),
        ),
    ]
