# Generated by Django 3.0 on 2019-12-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makas', '0016_auto_20191217_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postattachments',
            name='attachment',
            field=models.FileField(storage='post/', upload_to='post/'),
        ),
    ]
