# Generated by Django 3.0 on 2019-12-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makas', '0018_auto_20191217_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='attachments',
        ),
        migrations.CreateModel(
            name='PostsImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_tags', models.CharField(max_length=400)),
                ('attachment', models.FileField(upload_to='post/')),
                ('post_id', models.ManyToManyField(to='makas.Posts')),
            ],
        ),
    ]
