# Generated by Django 3.0 on 2019-12-18 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makas', '0019_auto_20191218_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PostImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='post/')),
            ],
        ),
        migrations.DeleteModel(
            name='PostsImages',
        ),
        migrations.AddField(
            model_name='post',
            name='postimages',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makas.PostImages'),
        ),
        migrations.AddField(
            model_name='post',
            name='posts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makas.Posts'),
        ),
        migrations.AddField(
            model_name='posts',
            name='images',
            field=models.ManyToManyField(to='makas.PostImages'),
        ),
    ]
