# Generated by Django 3.0 on 2019-12-18 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makas', '0020_auto_20191218_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='images',
        ),
        migrations.AddField(
            model_name='posts',
            name='images',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='makas.PostImages'),
            preserve_default=False,
        ),
    ]
