# Generated by Django 3.0 on 2020-02-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makas', '0024_auto_20200212_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
