# Generated by Django 3.0 on 2020-02-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makas', '0025_members_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='members',
            options={'managed': True, 'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
        migrations.AlterField(
            model_name='members',
            name='photo',
            field=models.ImageField(blank=True, upload_to='users/', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='postimages',
            name='attachment',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterModelTable(
            name='members',
            table='',
        ),
    ]
