# Generated by Django 3.0 on 2020-02-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makas', '0027_auto_20200212_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='images',
        ),
        migrations.AddField(
            model_name='posts',
            name='attachment',
            field=models.ImageField(blank=True, upload_to='post/', verbose_name='Post Attachment'),
        ),
    ]
