# Generated by Django 3.0 on 2020-02-12 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makas', '0028_auto_20200212_1628'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostImages',
        ),
    ]
