# Generated by Django 3.0 on 2020-02-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makas', '0029_delete_postimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='createdon',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
