# Generated by Django 3.0 on 2020-02-14 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makas', '0033_auto_20200213_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='makas.Posts'),
        ),
        migrations.CreateModel(
            name='PostLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.TextField()),
                ('createdon', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='makas.Posts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makas.Members')),
            ],
            options={
                'verbose_name': 'PostLike',
                'verbose_name_plural': 'PostLikes',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
