# Generated by Django 3.0 on 2020-02-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makas', '0034_auto_20200214_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlikes',
            name='like',
            field=models.IntegerField(),
        ),
    ]
