# Generated by Django 3.0.3 on 2020-02-23 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makas', '0037_remove_postlikes_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_to', models.IntegerField()),
                ('friend_action', models.CharField(default='no', max_length=6)),
                ('friend_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makas.Members')),
            ],
        ),
    ]
