# Generated by Django 3.0.3 on 2020-02-23 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makas', '0038_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='friend_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_from', to='makas.Members'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='friend_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_to', to='makas.Members'),
        ),
    ]
