# Generated by Django 3.0.3 on 2020-02-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makas', '0039_auto_20200223_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='friends',
            field=models.ManyToManyField(related_name='_members_friends_+', to='makas.Members'),
        ),
    ]
