# Generated by Django 3.0.3 on 2020-02-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makas', '0040_members_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='makas.Members'),
        ),
        migrations.AlterField(
            model_name='members',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_members_friends_+', to='makas.Members'),
        ),
    ]
